"""added a description to the course model

Revision ID: 0ed292624593
Revises: 52c1d527d0a7
Create Date: 2021-11-18 10:57:42.695840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed292624593'
down_revision = '52c1d527d0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###
