"""msg

Revision ID: 5eb6fab4a865
Revises: 2e2f5090abef
Create Date: 2021-11-18 16:25:02.060251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb6fab4a865'
down_revision = '2e2f5090abef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasklogin-users', sa.Column('is_superadmin', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flasklogin-users', 'is_superadmin')
    # ### end Alembic commands ###
