"""added is_admin field to User

Revision ID: 8b9d27b427bc
Revises: 0ed292624593
Create Date: 2021-11-18 13:16:43.182000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9d27b427bc'
down_revision = '0ed292624593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flasklogin-users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flasklogin-users', 'is_admin')
    # ### end Alembic commands ###
