"""Added creator_id to course

Revision ID: d73b44210f2f
Revises: 4767fc02f384
Create Date: 2021-11-25 09:31:48.323363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73b44210f2f'
down_revision = '4767fc02f384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'flasklogin-users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'creator_id')
    # ### end Alembic commands ###
